/** Modules generated by the deck Vite plugin from whatever is on disk. */

declare module 'virtual:slide-maker/deck' {
  import type { DeckConfig, SlideEntry } from './types';
  export const config: DeckConfig;
  export const slides: SlideEntry[];
}

declare module 'virtual:slide-maker/theme' {
  /** Name of the resolved template, or null if the configured one is missing. */
  export const template: string | null;
}

/** Injected by Vite's define. Distinguishes the studio from the exported deck. */
declare const __SM_MODE__: 'studio' | 'present';
