/** Modules generated by the Vite plugins from whatever is on disk. */

declare module 'virtual:slide-maker/deck' {
  import type { DeckConfig, SlideEntry } from './types';
  export const config: DeckConfig;
  export const slides: SlideEntry[];
}

declare module 'virtual:slide-maker/style' {
  /** Name of the resolved style, or null if the configured one is missing. */
  export const style: string | null;
}

declare module 'virtual:slide-maker/library' {
  import type { LibraryDeck, LibraryStyle, LibraryTemplate } from './types';
  /** The runtime stylesheet as text, layered under every style in a preview. */
  export const runtimeCss: string;
  export const templates: LibraryTemplate[];
  export const styles: LibraryStyle[];
  /** The deck browse was launched from, or null when it was launched elsewhere. */
  export const deck: LibraryDeck | null;
}

/** Injected by Vite's define. Distinguishes the studio from the exported deck. */
declare const __SM_MODE__: 'studio' | 'present' | 'browse';
